### ISSUE TITLE
endianess

### ISSUE THREAD

**Issue by steamraven** [3nsoft/xsp-files#1]
The documentation and the comment in the source indicate that all numbers are encoded little-endian, ie least significant bytes are stored first.  However, the code seems to be storing and reading in big-endian, ie most significant bytes first.

I believe staying with little-endian would be the best option, as most desktop processors are little endian, and in general big-endian processors also support little-endian.

**Comment by 3n-mb** [comment]
@steamraven you are correct. I should switch docs and comments to big-endian. Thank you for pointing this out.

Most of protocols are done big-endian way. NaCl's cipher is little-endian, and read efficiency there is more important, than efficiency of reading a header in the protocol.

**Comment by 3n-mb** [comment]
Fix is commited.
